language: node_js
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/reg_numbers_tests

node_js:
  - "8.10.0"

services:
  - postgresql

before_script:
  - psql -c 'create database  reg_numbers_tests;' -U postgres
  - psql -U postgres -d reg_numbers_tests -a -f database.sql

addons:
  apt:
    packages:
      - postgresql-server-dev-9.2